###Create User
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "Danielle Cristina",
  "email": "dani@teste.com",
  "password": "malukdete1",
  "type": 2
}


###Find All

GET http://localhost:3000/users


### Find One

GET http://localhost:3000/user/b2c5dccc-d40b-4b03-94f3-3eae3aaca96f