###Create User
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "Antonio",
  "email": "mjuslias@teste.com",
  "password": "malukdete1",
  "type": 1
}


###Find All

GET http://localhost:3000/users


### Find One

GET http://localhost:3000/user/


### Update User

PUT http://localhost:3000/user/
Content-Type: application/json

{
  "name": "Maria Julia",
  "email": "jmarcos@teste.com",
  "password": "malukdete1",
  "type": 1
}


###Delete User

DELETE http://localhost:3000/user/1